### ISSUE TITLE
Support for Enhanced Ecommerce Parameters

### ISSUE THREAD

**Issue by skwp** [tpitale/staccato#23]
I was trying to figure out how to extend staccato to support refunds but am somewhat confused.

The refund docs are here:
https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#enhancedecom

under "Measuring Refunds"

I was unclear how to create a class that would do the right thing. My first stab looked something like this

```ruby
      module Staccato
        class Refund
          include Staccato::Hit
          FIELDS = {
            transaction_id: 'ti',
          }

          def type
            :transaction # what goes here? how does stacatto know refunds vs purchases
          end
        end
      end
```

**Comment by nadavshatz** [comment]
Is this being actively worked on at the moment?

**Comment by tpitale** [comment]
Not really. Just looking now to check the status.

**Comment by tpitale** [comment]
I don't want to restrict Refund to being a non-interactive event only. It's unclear if it can be sent with other hit types. In addition, the unknown numeric values are annoying:

```
&pr1id=P12345                        // Product 1 ID. Either ID or name must be set.
&pr1nm=Android%20Warhol%20T-Shirt    // Product 1 name. Either ID or name must be set.
&pr1ca=Apparel                       // Product 1 category.
&pr1br=Google                        // Product 1 brand.
&pr1va=Black                         // Product 1 variant.
&pr1pr=29.20                         // Product 1 Price.
&pr1qt=1                             // Product 1 quantity.
```

**Comment by tpitale** [comment]
To fully support enhanced ecommerce:

* [ ] Measuring Impressions
* [ ] Measuring Actions
* [ ] Measuring Purchases
* [ ] Measuring Refunds
* [ ] Measuring the Checkout Process
* [ ] Measuring Internal Promotions

There's a lot of those keys with numbers in them. Google :shrugs:.

**Comment by tpitale** [comment]
Also, it seems all of these can be sent with other hit types (at least `events` and `pageviews`).

**Comment by tpitale** [comment]
## Product ##

Includes `pr` + `<productIndex>` +:

* id: `id`, text
* name: `nm`, text
* brand: `br`, text
* category: `ca`, text
* variant: `va`, text
* price: `pr`, currency (looks like a double?)
* quantity: `qt`, integer
* coupon code: `cc`, text
* position: `ps`, integer
* action: `pa`, text (detail, click, add, remove, checkout, checkout_option, purchase, refund)

And custom dimensions and custom metrics.

**Comment by tpitale** [comment]
## Transaction ##

Evidently not the hit type (maybe this changed?) Includes:

* All the stuff from `Transaction`
* coupon code: `tcc`, text

**Comment by tpitale** [comment]
## Checkout ##

When product action is set to 'checkout'

* step: `cos`, integer
* step option: `col`, text

**Comment by tpitale** [comment]
## Product Impression ##

### List Name ##

`il` + `<listIndex>` +:

* name: `nm`

With this name we can create product impressions

`il` + `<listIndex>` + `pi` + `<productIndex>` +:

* id: `id`, text
* name: `nm`, text
* brand: `br`, text
* category: `ca`, text
* variant: `va`, text
* position: `ps`, integer
* price: `pr`, currency

And custom dimension and custom metric.

**Comment by tpitale** [comment]
## Promotion ##

`promo` + `<promoIndex>` +:

* id: `id`, text
* name: `name`, text
* creative: `cr`, text
* position: `ps`, integer

And `promoa` for promotion action.

**Comment by tpitale** [comment]
So, I'm going to add `pa` for product action to the list of global options. Then, I'm thinking of making classes for each of these Enhanced Ecommerce features. My intention being that they should encapsulate these parameters, and be injected into any hit.

**Comment by nadavshatz** [comment]
Very interesting. Looks good. Would also be great to expose the affiliate and other params people might need. Let me know if you need any help and after you create one I can follow suite and make some others.

**Comment by tpitale** [comment]
@nadavshatz Can you link to the affiliate params you're referring to?

**Comment by nadavshatz** [comment]
@tpitale https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ta

There you go.

Also - https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#tcc could be useful.

**Comment by tpitale** [comment]
Both of those are in the lists above.

**Comment by nadavshatz** [comment]
Gotya, sorry about the confusion.

**Comment by tpitale** [comment]
No worries, I wanted to be sure I wasn't missing something.

**Comment by tpitale** [comment]
@skwp @nadavshatz Please try this out! https://github.com/tpitale/staccato/pull/25
