### ISSUE TITLE
Incorrect product impression prefix

### ISSUE THREAD

**Issue by rickyhanna** [tpitale/staccato#27]
https://github.com/tpitale/staccato/blob/master/lib/staccato/measurement/product_impression.rb#L14

```
'il' + list_index.to_s + 'pr' + index.to_s
```
Should be
```
'il' + list_index.to_s + 'pi' + index.to_s
```

According to this: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#il_pi_id

I've verified that the current prefix is incorrect by manually sending the request to /debug/collect using the generated params.

**Comment by tpitale** [comment]
Thanks for the PR #28.
