### ISSUE TITLE
Works with existing client-side Google Analytics cookies

### ISSUE THREAD

**Issue by arturoherrero** [tpitale/staccato#38]
I'm considering to replace [Gabba gem][1] with Staccato and its support of Universal Analytics.

One of the things I like to do is to identify the users with the `__utma` cookie, [like Gabba is doing][2].

I'm not sure if I can accomplish something similar reading the cookie manually or with [Google Analytics Cookie Parser][3] and then setting the global option `user_id`. Does it make sense?

Thank you! :wink: 

[1]: /hybridgroup/gabba
[2]: /hybridgroup/gabba#works-with-existing-client-side-google-analytics-cookies
[3]: /simonrobson/ga_cookie_parser

**Comment by tpitale** [comment]
I will try to take a look this weekend. Any ideas, code, suggestions welcome. Thanks!

**Comment by arturoherrero** [comment]
After read the documentation, I think that we can achieve the same using the `client_id`. I'm not sure if it's going to work but looks fine.

```ruby
client_id = cookies["_ga"].split(".").last(2).join(".")
tracker = Staccato.tracker('UA-XXXX-Y', client_id)
```

**Comment by tpitale** [comment]
Oh. Yes. The client id is analogous to the client id in the cookie.

It may or may not work due to other settings Google tracks around timestamps of pageviews. I'll be really curious to see what you find!

Closing this for now. Reopen if I can help with anything else.

**Comment by tpitale** [comment]
If it's what gabba uses, it will likely work.

**Comment by arturoherrero** [comment]
Using the `client_id` works for me after update the code in #40.

**Comment by mattty** [comment]
Advice from Google is to fetch the client ID using their getter, rather than inspect the cookie manually in case of breaking changes: https://developers.google.com/analytics/devguides/collection/analyticsjs/domains

@arturoherrero - Is that a concern at all? Is it worth passing the client ID back to the sever using their getter?

**Comment by tpitale** [comment]
If that's the case, you may want to capture the client id using JS, and pass it back to your Ruby code via params or some other means.
