### ISSUE TITLE
Requests in background-jobs

### ISSUE THREAD

**Issue by mintcore** [tpitale/staccato#43]
It seems that staccato currently halts the server while sending the request to GA. Is there any reason for this or is requests in another thread something worth considering?

**Comment by tpitale** [comment]
If you use something like https://github.com/httprb/http it will use threads in actors. This is much safer than just using a thread and is supported by Staccato:

1. https://github.com/tpitale/staccato#http-adapters
2. https://github.com/tpitale/staccato/blob/master/lib/staccato/adapter/http.rb
