### ISSUE TITLE
You're missing the screenview hit type

### ISSUE THREAD

**Issue by hugocore** [tpitale/staccato#46]
Just to let you guys know that you're missing the 'Screenview' hit type.

Check https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#t

This is an example from my app log that uses Google Analytics for iOS:

https://ssl.google-analytics.com/collect?av=1.0&cid=UUID&tid=UA-XXXX-1&dm=x86_64&cd=Name+of+view&t=screenview&aid=com.bundle.id&ul=en-us&_u=.nteoK9L&ds=app&sr=750x1334&v=1&_s=3&_crc=0&an=NAMEAPP&_v=mi3.1.3&ht=1441798811061&qt=998&z=10001206600962867553

**Comment by tpitale** [comment]
Thanks for the heads up. I'll add that shortly.
