### ISSUE TITLE
Accept unaliased attributes

### ISSUE THREAD

**Issue by tpitale** [tpitale/staccato#48]
If folks pass in a string key that isn't an alias, pass it on to google. For new attributes we haven't added to staccato yet.

**Comment by michaelminter** [comment]
+1

**Comment by tpitale** [comment]
Took a stab at this. Seems like because of the use of `Struct` for options it converts string keys to symbols. In addition, we have a current (perhaps accidental) feature where inappropriate global keys are ignored in the wrong hit type (e.g., event does not include hostname, it seems).

I'm still trying to figure out what the impact would be of dropping that accidental feature. If I can't drop it, I can't build this feature. I'm not sure which feature is more useful. I think the ability to ignore unknown arguments for a hit type.

Closing for now.
