### ISSUE TITLE
Ecommerce Custom Dimension

### ISSUE THREAD

**Issue by mdere** [tpitale/staccato#62]
Trying to understand how and if it  is possible to do custom dimensions for ecommerce tracker?

**Comment by tpitale** [comment]
https://github.com/tpitale/staccato#custom-dimensions-and-metrics

```ruby
hit = Staccato::Transaction.new(tracker, your_options_hash_here)
hit.add_custom_dimension(1, 'Shirts')
hit.track!
```

**Comment by tpitale** [comment]
Here's a new section in the readme: https://github.com/tpitale/staccato#building-hits

**Comment by mdere** [comment]
@tpitale - ah ok. thanks

**Comment by mdere** [comment]
@tpitale - Just making sure - So I was doing this at first

```
tracker = Staccato.tracker(gcode)
tracker.transaction(hash)
```

are there any differences with your approach vs this approach?

**Comment by tpitale** [comment]
Yes. That builds and tracks the hit in one call. Does not include custom dimensions/metrics.

**Comment by mdere** [comment]
@tpitale - so to make sure I understand this functionality - this will create a custom secondary dimension for the transaction?

I can find this dimension under the "Custom Variable" section of the Secondary Dimension drop down right? It should be there until GA finishes processing my transaction request right?

**Comment by tpitale** [comment]
@mdere: I haven't personally used customer dimensions with transactions, so I can't answer that question. Staccato follows the spec (https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cd_).
