### ISSUE TITLE
Enhanced ecommerce?

### ISSUE THREAD

**Issue by nicpillinger** [tpitale/staccato#63]
Hey there, have been trying to use the gem to push some transaction information to Universal Analytics - I need to push transaction and refund data. I've created a transaction with build_transaction then added measurements for the transaction info and product but we're not getting any product info coming through in GA? Can we mimic this https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#measuring-transactions
using staccato?

Thanks for any help.

**Comment by tpitale** [comment]
1. The link you shared is for JS. GA does not necessarily provide the same functionality for the collection API. Here's a link to the official measurement protocol that Staccato uses: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters

2. Here are links to the sections of the README. https://github.com/tpitale/staccato#transaction-w-product https://github.com/tpitale/staccato#transaction-refund https://github.com/tpitale/staccato#transaction--product-refund

3. If you're not seeing data tracked, please open an issue and share some example of your code, I'd be happy to help if there is a bug in Staccato.
