### ISSUE TITLE
How to set SSL?

### ISSUE THREAD

**Issue by skwp** [tpitale/staccato#67]
https://github.com/tpitale/staccato/blob/f73535fc0e428db10f583a2f7371b2165869a224/lib/staccato.rb#L39

There appears to be a way to pass in an ssl attribute into this method but no public way to configure stacatto to use SSL. Is it defaulting to non-SSL google analytics access? Not clear from reading the code. Wanted to bring this up for discussion before doing any kind of work.

**Comment by tpitale** [comment]
You could do it this way:

```ruby
tracker = Staccato.tracker('UA-XXXX-Y') do |c|
  c.adapter = Staccato::Adapter::HTTP.new(Staccato.ga_collection_uri(true))
end
```

But, I should probably make it easier to set that.

**Comment by tpitale** [comment]
@skwp I just release v0.4.7, which let's you pass `ssl: true` when building a new tracker.

**Comment by skwp** [comment]
Awesome sauce thanks for the quick reply
