### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by jmscholen** [tpitale/staccato#68]
Issue originally posted in the  staccoto-rails gem: https://github.com/tpitale/staccato-rails/issues/11 

Reissued here:
This is the first that I have installed this gem. This is not happening on my local when I am loading the page that I am trying to have events tracked, but when I push to our staging environment and I load the page where the tracker has been placed, it redirects at the code:
tracker.event(category: 'staging', action: 'index', label: 'test', value: 1)

**Comment by tpitale** [comment]
So, to continue our conversation: what is "it" that is redirecting …?

**Comment by jmscholen** [comment]
Not sure what I did when I set it up last. I started from scratch today and its working great. Sorry for the foobar!

Thanks for your patience!
