### ISSUE TITLE
`Staccato.as_url` does not honour tracker SSL setting

### ISSUE THREAD

**Issue by svoop** [tpitale/staccato#69]
Just found this odd behaviour while debugging:

    tracker = Staccato.tracker('UA-XXXX-Y', nil, ssl: true)   # => @ssl=true
    event = tracker.build_event(category: 'video', action: 'play', label: 'cars', value: 1)   # => @ssl=true
    Staccato.as_url(event)
    # => "http://www.google-analytics.com/collect?v=1&tid=UA-XXXX-Y&..."

IMO, the expected behaviour is `Staccato.as_url` to honour the SSL setting and return a "https://sss.google-analytics.com" based URL.

**Comment by tpitale** [comment]
I've created a PR to resolve this. You should know, however, that `as_url` is really only advisable as a debugging tool. It is expected that you would call `event.track!`. I'll have to update the docs to mention `as_url` is for debugging.

**Comment by tpitale** [comment]
Released gem v0.5.0.

**Comment by svoop** [comment]
@tpitale Thanks a bunch, that was fast!
