### ISSUE TITLE
Asynchronously track: what should I use?

### ISSUE THREAD

**Issue by fernandobrito** [tpitale/staccato#72]
Hello,

Just started using this gem today. Great work on it!

What do people usually use to run the tracker asynchronously? I found a ticket suggesting using a HTTP adapter that supports it (#43), but I would like to know if there would be any downside on integrating staccato with sucker_punch (already used on my project), for example. Would there be any interest on integrating it with staccato? I can try to work on that.

Thank you

**Comment by tpitale** [comment]
You can just use a background job if you want to, but I suspect that's much more work. Either way, no need for code in Staccato.

**Comment by tpitale** [comment]
Simply use https://github.com/httprb/http.rb and the appropriate adapter as described in the readme and you should be good to go.

**Comment by tpitale** [comment]
https://github.com/tpitale/staccato#http-adapters

Replace "Faraday" with "HTTP". And require staccato/adapter/http
