### ISSUE TITLE
Unrecognized paramteter '_anon_uip' found.

### ISSUE THREAD

**Issue by viktors** [tpitale/staccato#73]
When I try to run the following code:

```
require 'staccato'
require 'staccato/adapter/logger'
require 'staccato/adapter/validate'

tracker = Staccato.tracker('UA-XXXXXXXX-Y') do |c|
  c.adapter = Staccato::Adapter::Validate.new
end

puts tracker.pageview(path: '/', user_ip: '127.0.0.1')

```

I get the following output:
```
{
  "hitParsingResult": [ {
    "valid": true,
    "parserMessage": [ {
      "messageType": "INFO",
      "description": "Unrecognized paramteter '_anon_uip' found.",
      "messageCode": "UNKNOWN_PARAMETER",
      "parameter": "_anon_uip"
    } ],
    "hit": "/debug/collect?v=1\u0026tid=UA-11773596-2\u0026cid=4a767679-46ac-41b4-a6b4-898b5cf8c50f\u0026t=pageview\u0026uip=xxxxxxxxx\u0026dp=/\u0026_anon_uip=127.0.0.0"
  } ],
  "parserMessage": [ {
    "messageType": "INFO",
    "description": "Found 1 hit in the request."
  } ]
}
```

It started happening on 18th Nov 2016 - looks like a change in GA API.

**Comment by tpitale** [comment]
I think it's the way Json is serializing the query params &.

**Comment by tpitale** [comment]
Or rather the & in the hut is encoded and I expect broken. May be a change in Ruby. I first noticed with 2.2.4.

**Comment by tpitale** [comment]
@viktors Can you try the logger adapter and see if that param _anon_uip is being sent by staccato?

I can't find where in the code that is happening. It may be on GA side, or just a bad error message.

**Comment by tpitale** [comment]
`D, [2016-11-23T14:45:27.543603 #86867] DEBUG -- : v=1 tid=UA-XXXXXXXX-Y cid=f5bf5b51-9ea6-49c6-b69f-2472a62622b0 t=pageview uip=127.0.0.1 dp=/`

Is what I get when I use the logger adapter. No `_anon_uip`.

**Comment by tpitale** [comment]
It seems like maybe this is something GA does automatically for `uip`: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#uip … no idea why they're rejecting the field wholesale.

**Comment by tpitale** [comment]
The `hit` is still considered valid (as seen in the output shared in the issue). I don't believe there is a way for us to fix this on our end, and it should not prevent data from being tracked.

Sorry I can't do more.

**Comment by tpitale** [comment]
To be clear, I can reproduce and I do see the same message. Regardless of ruby version (it's only the output that has the & encoding).
