### ISSUE TITLE
Multiple adapters?

### ISSUE THREAD

**Issue by elsurudo** [tpitale/staccato#74]
I'm currently trying to debug a production issue (tracked pageviews aren't showing up in my GA account), but it seems I can either log, OR send the pageview.

Perhaps it would make sense to allow multiple adapters, with the ability to post to all of them? I also don't get the point of the ValidateAdapter, since there is no way to see the output (I thought that was the whole point of sending to the GA debug endpoint)?

Other than that, any help with debugging missing pageviews would be greatly appreciated (when I log, things look fine).

**Comment by tpitale** [comment]
Multiple adapters isn't a bad idea. PRs welcome.

**Comment by tpitale** [comment]
Validation adapter output:

```ruby
puts tracker.pageview(path: '/')
```

```json
{
  "hitParsingResult": [ {
    "valid": false,
    "parserMessage": [ {
      "messageType": "ERROR",
      "description": "The value provided for parameter 'tid' is invalid. Please see http://goo.gl/a8d4RP#tid for details.",
      "messageCode": "VALUE_INVALID",
      "parameter": "tid"
    } ],
    "hit": "/debug/collect?v=1\u0026tid=UA-XXXX-Y\u0026cid=c0e65451-8118-48c0-8c55-68949b050ab9\u0026t=pageview\u0026dp=/"
  } ],
  "parserMessage": [ {
    "messageType": "INFO",
    "description": "Found 1 hit in the request."
  } ]
}
```

**Comment by tpitale** [comment]
@elsurudo What do you think of that PR? It's a fairly simplistic implementation.

**Comment by elsurudo** [comment]
@tpitale Nice, looks good. Just had one comment to make on the PR. 

Thanks for the tip regarding the ValidateAdapter. Stupidly, I didn't think of printing the output, and was expecting there to be a log call in the adapter itself.
