### ISSUE TITLE
Not seeing events in Google Analytics

### ISSUE THREAD

**Issue by markcerqueira** [tpitale/staccato#76]
Hi! Thanks for the awesome library! I'm having an issue and can't seem to get around it.

I set up a new "mobile app" in the Google Analytics admin panel, got the tracking id (e.g. UA-ABCDEFGH-1), added staccato to a Sinatra project, and am tracking events. Commit is [here][1].

I then go to the [Google Analytics site](https://analytics.google.com/analytics/web/#home), but don't see any events there.

Am I missing something? Thank you!

[1]: https://github.com/markcerqueira/chuckpad-social/commit/d742a71ad8fd3a5257e293fb6b18c70f902decd8

**Comment by tpitale** [comment]
Your code is not calling staccato properly.

`tracker.track…` is not a thing. You probably want `tracker.event…`.

**Comment by markcerqueira** [comment]
Gah! That was very dumb of me. Everything is working a-okay after that change. Thank you very much and happy holidays!
