### ISSUE TITLE
Google Analytic Real Time is wrong

### ISSUE THREAD

**Issue by Etienne-C** [tpitale/staccato#77]
Hi,

I begin to use stacato for my Rails App, and i have all tame the same issue.
When a event is fired that automaticaly add a user in the realtime dashboard (in the screen you can see 4 users, but only 3 active pages), the adding visit seems located from Ashburn (USA) . 
Is not a GA error, because i already have 30 visitors on GA realtime dashboard whereas in reality just 2 visitors were on the site.
![image](https://cloud.githubusercontent.com/assets/8225279/26360755/592b28a8-3faf-11e7-849e-12ad0f3d061b.png)

My code: 
Model User for track signup
```
class User < ApplicationRecord
   after_create :tracking_user_signup

   def tracking_user_signup
      tracker = Staccato.tracker('UA-XXXXXXX-X', nil, ssl: true)
      tracker.event(category: 'User', action: 'Signup', label: "Signup", value: nil)
   end
end
```

The event is well fired on GA:
![image](https://cloud.githubusercontent.com/assets/8225279/26361059/2f32ea08-3fb0-11e7-9eb0-60926560be6e.png)

So, any idea? 
Thx

**Comment by tpitale** [comment]
Unless you are proxying the IP address of the user of your site … GA see it coming from the IP of server your code is running on and does a lookup on that.
