### ISSUE TITLE
Multiple products quantity 

### ISSUE THREAD

**Issue by Yakubiv** [tpitale/staccato#80]
I have a problem when creating pageview for one transaction and 4 products with quantity 1.
For some reason it creates 4 products with quantity 2, and 8 in total for transaction.

```
pageview = tracker.build_pageview(path: '/receipt', hostname: 'test.com',
                                      title: 'Money', product_action: 'purchase')
    pageview.add_measurement(:transaction, transaction_params)
    products.each_with_index do |product, index|
      index += 1
      transaction_item = { index: index, id: "1-#{product.id}",
                           name: product.name,
                           price: product.price,
                           quantity: 1,
                           position: index,
                           category: product.url_alias }
      pageview.add_measurement(:product, transaction_item)
 end
    pageview.track!
```

**Comment by tpitale** [comment]
Not enough information to debug. It is unlikely to be an issue with staccato.

If you wish, you can share the tracking (URL) output that is generated from your pageview. https://github.com/tpitale/staccato#logger-adapter-for-local-developmentdebugging

**Comment by Yakubiv** [comment]
I fixed it by removing quantity: 1 from transaction_item, the total transactions quantity is correct after that.

**Comment by Yakubiv** [comment]
But it seems like item transaction creating 2 times per each product.
