### ISSUE TITLE
Rack middleware

### ISSUE THREAD

**Issue by gingermusketeer** [tpitale/staccato#82]
It would be great to be able to easily add rack middleware to get pageview tracking information with this gem.

Do you think it would make sense to include this?

I have something like the following at the moment:
```ruby
class StaccatoRack
  def initialize(app)
    @app = app
  end

  def call(env)
    track_pageview(env)
    @app.call(env)
  end

  def track_pageview(env)
    host = env["HTTP_HOST"]
    path = env["PATH_INFO"]
    tracker.pageview(path: path, hostname: host)
  end

  def tracker
    @tracker ||= Staccato.tracker(ENV["GA_ANALYTICS_ID"])
  end
end
```

**Comment by tpitale** [comment]
I built a project like this: https://github.com/tpitale/staccato-rails. You are more than welcome to make a gem for `staccato-rack`, or a PR to `staccato-rails` to add a rack middleware option/feature would be appreciated.

I'm hoping to keep this project agnostic to other frameworks.

**Comment by gingermusketeer** [comment]
Your rails gem looks like what I was after. Would it make sense to link to that one near the top of the read me?

Thanks for letting me know about it. I will try it out.

**Comment by tpitale** [comment]
I can add something to the readme.

**Comment by tpitale** [comment]
Link added: https://github.com/tpitale/staccato/commit/fb79fa0e95474cc13c5981f852ce7b3f2de44822

**Comment by gingermusketeer** [comment]
Awesome 🙂
