### ISSUE TITLE
How to add utt to events?

### ISSUE THREAD

**Issue by trddddd** [tpitale/staccato#90]
How i can add timing 'utt=' include to transaction or event?

**Comment by trddddd** [comment]
its stupid monkeypatch
```ruby
# frozen_string_literal: true

module Staccato
  module Hit
    ORIGINAL_GLOBAL_OPTIONS = GLOBAL_OPTIONS.dup

    remove_const(:GLOBAL_OPTIONS) if defined?(GLOBAL_OPTIONS)

    GLOBAL_OPTIONS = ORIGINAL_GLOBAL_OPTIONS.merge!(time: "utt").freeze

    remove_const(:ORIGINAL_GLOBAL_OPTIONS) if defined?(ORIGINAL_GLOBAL_OPTIONS)
  end

  module Measurement
    class Timing
      # lookup key for use in Hit#add_measurement
      # @return [Symbol]
      def self.lookup_key
        :timing
      end

      # Transaction measurement options fields
      FIELDS = {
        time: 'utt'
      }.freeze

      include Measurable
    end

    TYPES = Hash[
      [
        Checkout,
        CheckoutOption,
        ImpressionList,
        Product,
        ProductImpression,
        Promotion,
        Transaction,
        Timing,
      ].map { |k| [k.lookup_key, k] }
    ].freeze
  end
end
````

**Comment by tpitale** [comment]
https://github.com/tpitale/staccato/blob/de2f93b5ce59a4e8eaadf6f4390ffd0db9c1642d/lib/staccato/timing.rb#L10

**Comment by tpitale** [comment]
Are you saying `Timing` isn't in the list of measurements here? https://github.com/tpitale/staccato/blob/de2f93b5ce59a4e8eaadf6f4390ffd0db9c1642d/lib/staccato/measurement.rb#L16

**Comment by tpitale** [comment]
`Timing` is a hit type of its own. Can you provide docs that say `utt` is a global option?

**Comment by tpitale** [comment]
The docs say that `utt` is only for `Timing`: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#utt

**Comment by trddddd** [comment]
thanks for the explanation)

**Comment by trddddd** [comment]
> `Timing` is a hit type of its own. Can you provide docs that say `utt` is a global option?

[hitbuilder](https://ga-dev-tools.appspot.com/hit-builder/) says that the syntax is valid if you select the type of event or pageview. 
And this is a little misleading

**Comment by tpitale** [comment]
I see that I can make that … I'm not sure what GA will do with that information. I can't find information in the docs that says if it would just be ignored or what.
